"""Emit the payload the two pages read.

The explorer has to work when someone opens tool.html straight off disk. Every
browser blocks fetch() against a file:// URL, so a page that fetched its own
JSON would render an error for exactly the reader who cloned the repo and double
clicked the file. A <script src> is not blocked, so the site payload is written
as a JavaScript file that assigns one global.

data/findings.json stays the canonical record and is what everything else in the
pipeline reads and writes. data/site.js is generated from it, carries only the
fields the explorer draws, and is regenerated by run.sh, so the two cannot drift.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
GRAPH = DATA / "graph"

KEEP = (
    "id", "type", "demand", "concept", "concept_label", "concept_kind",
    "section", "section_heading", "doc_title", "doc_url", "section_path",
    "section_lines", "missing", "proof_path", "questions", "question_titles",
    "confirming_answer", "validated", "validation_note", "gap_note", "requires_count",
    "mentions_count", "requires_evidence_kind", "sections_referencing",
    "answer_holder", "rival", "in_edges_total",
)

SOURCE_BASE = "https://github.com/fastapi/fastapi/blob"


def read(name: str, default=None):
    path = DATA / name
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    findings = read("findings.json", {"findings": [], "counts": {}})
    manifest = read("manifest.json", {})
    validation = read("validation.json", {})
    answers = read("answers.json", {})
    nodes = json.loads((GRAPH / "nodes.json").read_text(encoding="utf-8"))["nodes"]

    questions = {
        n["id"]: {"title": n["title"], "url": n["url"], "number": n["number"]}
        for n in nodes if n["type"] == "Question"
    }
    sections = {
        n["id"]: {"heading": n["heading"], "doc_title": n["doc_title"], "url": n["url"],
                  "path": n["path"], "lines": n["lines"]}
        for n in nodes if n["type"] == "Section"
    }

    trimmed = []
    for finding in findings["findings"]:
        entry = {k: finding[k] for k in KEEP if k in finding}
        entry["question_links"] = [
            {"id": qid, **questions[qid]} for qid in finding.get("questions", [])[:12]
            if qid in questions
        ]
        trimmed.append(entry)

    payload = {
        "generated_from": "data/findings.json",
        "source_base": f"{SOURCE_BASE}/{manifest.get('corpus_commit', 'master')}",
        "counts": findings.get("counts", {}),
        "manifest": manifest,
        "validation": validation.get("by_type", {}),
        "answers_summary": answers.get("summary", {}),
        "sections": sections,
        "findings": trimmed,
    }

    out = DATA / "site.js"
    out.write_text(
        "/* Generated by pipeline/site_data.py from data/findings.json.\n"
        "   Do not edit. A <script src> is used rather than fetch() so the\n"
        "   explorer works when tool.html is opened straight off disk. */\n"
        "window.SMAA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    size = out.stat().st_size
    print(f"Wrote data/site.js: {len(trimmed)} findings, {size / 1024:.0f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
